# Introduction to NumPy

## Step 1 – Understand the Concept

### What is NumPy?

NumPy stands for Numerical Python. It is a Python library used mainly for working with numerical data, arrays, and mathematical operations.

NumPy provides a special data structure called `ndarray`, which allows us to store and process multiple numerical values efficiently.


## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

A calculator helps us perform calculations on numbers quickly.

Similarly, NumPy acts like a numerical computing tool in Python that helps us work with numerical data and perform calculations.

### 2. Simple Example

Suppose we have student marks:

80, 75, 90, 85, 70

We can store these marks in a NumPy array and perform calculations such as average, maximum, and minimum.

### 3. Business Example

An e-commerce company has customer purchase amounts:

₹500, ₹750, ₹1200, ₹450, ₹900

NumPy can help process this numerical data and perform calculations such as average purchase amount and highest purchase.

### 4. AI/ML Use Case

A Machine Learning dataset may contain numerical features such as age, salary, and experience.

NumPy arrays can be used to store and process these numerical values during data preparation and numerical computation.

In [4]:
# Import NumPy
import numpy as np

# Create a NumPy array
marks = np.array([80, 75, 90, 85, 70])

# Display the array
print(marks)

[80 75 90 85 70]


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array()` creates a NumPy array from the given values.
- `marks` stores the created NumPy array.
- `print(marks)` displays the values in the array.

### What does the code do?

The code imports NumPy, creates a NumPy array containing five student marks, stores it in the `marks` variable, and displays the array.

### Why is the function or method used?

`np.array()` is used to create a NumPy array because NumPy arrays are designed for storing and processing numerical data efficiently.

### Expected Output

The output is:

`[80 75 90 85 70]`

### Where is this concept used in AI/ML or Data Analytics?

NumPy is used for numerical calculations, data processing, data preprocessing, mathematical operations, handling numerical datasets, and preparing numerical data for Machine Learning.

# Why NumPy?

## Step 1 – Understand the Concept

NumPy is useful because it provides efficient arrays and makes numerical operations easier.

Compared with normal Python lists, NumPy allows us to perform mathematical operations directly on arrays.

For example, adding 5 to every value in a NumPy array can be done directly without writing a loop.

## Step 2 – Demonstrate the Concept

### Real-World Analogy

A calculator can perform the same calculation on multiple values quickly instead of calculating each value separately.

### Simple Example

Suppose we have:

`[10, 20, 30, 40, 50]`

Adding 5 to the array gives:

`[15, 25, 35, 45, 55]`

### Business Example

A company may need to increase the prices of many products by ₹5. NumPy can perform this operation on an entire array of prices.

### AI/ML Use Case

Machine Learning datasets contain many numerical values. NumPy helps perform numerical operations on these values efficiently during data processing and preprocessing.

In [5]:
# Import NumPy
import numpy as np

# Create an array of marks
marks = np.array([80, 75, 90])

# Add 5 to every mark
updated_marks = marks + 5

# Display the updated marks
print(updated_marks)

[85 80 95]


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library.
- `np.array()` creates a NumPy array containing the student marks.
- `marks + 5` adds 5 to every value in the array.
- `updated_marks` stores the updated values.
- `print(updated_marks)` displays the result.

### What does the code do?

The code creates a NumPy array of student marks and adds 5 to every mark at the same time.

### Why is the operation used?

`marks + 5` is used to apply the same numerical operation to every element of the NumPy array without using a loop.

### What output is expected?

The output is:

`[85 80 95]`

Each original mark has increased by 5.

### Where is this concept used in AI/ML or Data Analytics?

This type of array operation is used when performing numerical calculations and data preprocessing on large datasets.

## NumPy Arrays (`ndarray`)

## Step 1 – Understand the Concept

A NumPy array is a data structure used to store multiple values in an organized form.

NumPy arrays are created using `np.array()`.

The main array structure in NumPy is called `ndarray`, which means N-dimensional array.

An array can have different dimensions, such as 1D, 2D, or 3D.

## Step 2 – Demonstrate the Concept

### Real-World Analogy

A row of lockers can be compared to a 1D array, where each locker stores one value.

### Simple Example

A 1D array can store a sequence of numbers:

`[10, 20, 30, 40]`

### Business Example

A company can store the daily sales of four days in a NumPy array:

`[1000, 1500, 1200, 1800]`

### AI/ML Use Case

Machine Learning data can contain multiple numerical features. NumPy arrays can store these numerical values in an organized structure for processing.

In [6]:
# Import NumPy
import numpy as np

# Create a NumPy array
data = np.array([10, 20, 30, 40])

# Display the array
print(data)

# Display the type of the array
print(type(data))

[10 20 30 40]
<class 'numpy.ndarray'>


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library.
- `np.array()` creates a NumPy array from the given values.
- `data` stores the NumPy array.
- `print(data)` displays the values in the array.
- `type(data)` shows the data type of the object.

### What does the code do?

The code creates a NumPy array containing four numerical values and checks that the created object is a NumPy `ndarray`.

### Why is the function or method used?

`np.array()` is used to create a NumPy array.

`type()` is used to identify the type of the created object.

### What output is expected?

The first output displays the array values:

`[10 20 30 40]`

The second output confirms that the object is a NumPy `ndarray`.

### Where is this concept used in AI/ML or Data Analytics?

NumPy arrays are used to store and process numerical data in data preprocessing, numerical calculations, and Machine Learning workflows.

## Creating Arrays

## Step 1 – Understand the Concept

NumPy arrays can be created in different ways depending on the type of data we need.

The `np.array()` function is used to create a NumPy array from existing values.

Other useful NumPy functions for creating arrays include:

- `np.zeros()` – creates an array filled with zeros.
- `np.ones()` – creates an array filled with ones.
- `np.arange()` – creates an array with values in a specified range.

These functions make it easier to create arrays for numerical data processing.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Think about arranging items in a set of boxes.

If we already have items, we can place them into the boxes. If we need empty boxes with a default value, we can create them first.

Similarly, NumPy provides different functions to create arrays based on the values or structure we need.

### 2. Simple Example

Suppose we have the numbers:

`10, 20, 30, 40`

We can use `np.array()` to create a NumPy array from these values.

Result:

`[10 20 30 40]`

### 3. Business Example

A company may need to store the sales amounts of five products.

For example:

`[5000, 7000, 4500, 8000, 6500]`

We can create a NumPy array from these sales values and use it for further numerical calculations.

### 4. AI/ML Use Case

During Machine Learning data preparation, we may need to convert numerical values into NumPy arrays so that they can be processed and used in numerical calculations.

In [7]:
# Import NumPy
import numpy as np

# Create a NumPy array
numbers = np.array([10, 20, 30, 40])

# Display the array
print(numbers)

[10 20 30 40]


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library.
- `np.array()` creates a NumPy array from the given values.
- `numbers` stores the created NumPy array.
- `print(numbers)` displays the array.

### What does the code do?

The code creates a NumPy array containing the values 10, 20, 30, and 40 and displays the array.

### Why is the function or method used?

`np.array()` is used to create a NumPy array from existing values.

### What output is expected?

The output is:

`[10 20 30 40]`

### Where is this concept used in AI/ML or Data Analytics?

Creating NumPy arrays is useful when preparing numerical data for calculations, data processing, and Machine Learning workflows.

## Dimensions

## Step 1 – Understand the Concept

The dimension of a NumPy array tells us how many axes or levels the array has.

A 1D array has one axis and stores values in a single row.

A 2D array has two axes and stores values in rows and columns, similar to a table.

A 3D array has three axes and can contain multiple 2D arrays.

NumPy provides the `.ndim` attribute to find the number of dimensions of an array.

We can also use the `np.ndim()` function to find the number of dimensions.

Dimensions are important because they help us understand how numerical data is structured before performing calculations or using it in AI/ML models.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Think about storage shelves.

- One row of items represents a 1D structure.
- A shelf with multiple rows and columns represents a 2D structure.
- Multiple shelves placed together can represent a 3D structure.

The number of levels used to organize the items is similar to the number of dimensions in an array.

### 2. Simple Example

A 1D array:

`[10, 20, 30, 40]`

It contains values in one direction, so it has 1 dimension.

A 2D array:

`[[10, 20], [30, 40]]`

It contains rows and columns, so it has 2 dimensions.

### 3. Business Example

A company may store daily sales in a 1D array:

`[5000, 7000, 6000, 8000]`

If the company stores sales for multiple products across multiple months, it can use a 2D array where rows represent products and columns represent months.

This makes the data easier to organize and analyze.

### 4. AI/ML Use Case

In AI/ML, datasets are commonly represented as 2D arrays.

For example, each row can represent one customer and each column can represent a feature such as age, income, or purchase amount.

Understanding dimensions helps us provide data in the correct structure to machine learning algorithms.

In [8]:
# Import NumPy
import numpy as np

# Create a 1D array
one_d = np.array([10, 20, 30, 40])

# Create a 2D array
two_d = np.array([[10, 20], [30, 40]])

# Find the dimensions
print(one_d.ndim)
print(two_d.ndim)

1
2


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([10, 20, 30, 40])` creates a 1D NumPy array because the values are arranged in a single level.
- `np.array([[10, 20], [30, 40]])` creates a 2D NumPy array because the values are arranged into rows and columns.
- `one_d.ndim` checks how many dimensions the `one_d` array has.
- `two_d.ndim` checks how many dimensions the `two_d` array has.
- `print()` displays the dimension values.

### What the Code Does

The code creates two NumPy arrays with different structures and checks their number of dimensions.

The first array is 1D, while the second array is 2D.

### Why `.ndim` is Used

The `.ndim` attribute is used to find the number of dimensions or axes in a NumPy array.

It helps us understand the structure of the data before performing calculations or passing the data to other processes.

`.ndim` is an attribute, so we write:

`array.ndim`

and not:

`array.ndim()`

### Expected Output

```text
1
2

## Shape

## Step 1 – Understand the Concept

The shape of a NumPy array tells us the number of elements along each dimension.

For a 1D array, the shape tells us how many values are present.

For a 2D array, the shape tells us the number of rows and columns.

For example, an array with 2 rows and 3 columns has a shape of `(2, 3)`.

NumPy provides the `.shape` attribute to find the shape of an array.

The `shape` attribute is useful for understanding the structure and size of data before performing operations or using it in AI/ML models.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Think about a classroom.

If there are 3 rows of desks and each row has 4 desks, the arrangement can be described as 3 rows and 4 columns.

Similarly, the shape of a 2D NumPy array tells us how many rows and columns are present.

### 2. Simple Example

Consider this 2D array:

`[[10, 20, 30], [40, 50, 60]]`

It has:

- 2 rows
- 3 columns

Therefore, its shape is `(2, 3)`.

### 3. Business Example

A company may store sales data for 4 products across 3 months.

The data can be organized as:

- Rows → Products
- Columns → Months

The shape would be `(4, 3)`.

This helps the company understand how the sales data is organized.

### 4. AI/ML Use Case

In AI/ML, datasets are often stored as 2D arrays.

For example, if a dataset contains 100 customers and 5 features for each customer, the shape can be `(100, 5)`.

Here:

- `100` represents the number of samples.
- `5` represents the number of features.

Checking the shape helps us make sure the data has the expected structure before training a machine learning model.

In [9]:
# Import NumPy
import numpy as np

# Create a 1D array
one_d = np.array([10, 20, 30, 40])

# Create a 2D array
two_d = np.array([[10, 20, 30], [40, 50, 60]])

# Find the shape of the arrays
print(one_d.shape)
print(two_d.shape)

(4,)
(2, 3)


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([10, 20, 30, 40])` creates a 1D NumPy array containing 4 values.
- `np.array([[10, 20, 30], [40, 50, 60]])` creates a 2D NumPy array with 2 rows and 3 columns.
- `one_d.shape` returns the shape of the 1D array.
- `two_d.shape` returns the shape of the 2D array.
- `print()` displays the shape values.

### What the Code Does

The code creates one 1D array and one 2D array and checks the structure of each array using the `.shape` attribute.

The 1D array contains 4 values, while the 2D array contains 2 rows and 3 columns.

### Why `.shape` is Used

The `.shape` attribute is used to understand how data is arranged inside a NumPy array.

It is especially useful when working with datasets because we can quickly check the number of rows, columns, or values in each dimension.

`.shape` is an attribute, so we write:

`array.shape`

We do not write:

`array.shape()`

### Expected Output

```text
(4,)
(2, 3)


### Where It Is Used in AI/ML or Data Analytics

The .shape attribute is commonly used to check the structure of datasets before analysis or model training.

For example, if a customer dataset contains 1,000 customers and 6 features, its shape can be:

(1000, 6)

Here:

1000 represents the number of samples or customers.
6 represents the number of features.

Checking the shape helps us verify that the data has the expected structure before giving it to a machine learning model or performing data analysis.

## Size

## Step 1 – Understand the Concept

The size of a NumPy array tells us the total number of elements present in the array.

For a 1D array, the size is the total number of values.

For a 2D array, the size is the total number of values across all rows and columns.

NumPy provides the `.size` attribute to find the total number of elements in an array.

The `.size` attribute is different from `.shape`.

- `.shape` tells us the structure of the array.
- `.size` tells us the total number of elements in the array.

The `.size` attribute is useful when we need to know how much data is stored in an array.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Think about a classroom with 3 rows and 4 desks in each row.

The shape of the classroom arrangement is 3 rows and 4 columns.

The total number of desks is:

`3 × 4 = 12`

Similarly, the size of a NumPy array tells us the total number of elements stored in it.

### 2. Simple Example

Consider this 2D array:

`[[10, 20, 30], [40, 50, 60]]`

It has:

- 2 rows
- 3 columns
- 6 total elements

Therefore:

- Shape → `(2, 3)`
- Size → `6`

### 3. Business Example

A company stores sales data for 5 products across 4 months.

The array has:

- 5 rows representing products
- 4 columns representing months

The shape is `(5, 4)`.

The total number of sales values is:

`5 × 4 = 20`

So, the size of the array is `20`.

### 4. AI/ML Use Case

In AI/ML, a dataset may contain many samples and features.

For example, a dataset with 100 customers and 5 features has a shape of `(100, 5)`.

Its total number of values is:

`100 × 5 = 500`

The `.size` attribute can be used to find the total number of elements stored in the dataset.

In [10]:
# Import NumPy
import numpy as np

# Create a 1D array
one_d = np.array([10, 20, 30, 40])

# Create a 2D array
two_d = np.array([[10, 20, 30], [40, 50, 60]])

# Find the size of the arrays
print(one_d.size)
print(two_d.size)

4
6


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([10, 20, 30, 40])` creates a 1D NumPy array containing 4 values.
- `np.array([[10, 20, 30], [40, 50, 60]])` creates a 2D NumPy array with 2 rows and 3 columns.
- `one_d.size` finds the total number of elements in the 1D array.
- `two_d.size` finds the total number of elements in the 2D array.
- `print()` displays the size values.

### What the Code Does

The code creates two NumPy arrays and finds the total number of elements stored in each array.

The first array contains 4 elements.

The second array contains 2 rows and 3 columns, so it contains 6 elements in total.

### Why `.size` is Used

The `.size` attribute is used to find the total number of elements present in a NumPy array.

It is useful when we need to understand how much data is stored in an array.

`.size` is an attribute, so we write:

`array.size`

We do not write:

`array.size()`

### Expected Output

```text
4
6 

4 means the first array contains 4 elements.

6 means the second array contains 6 elements in total.

### Where It Is Used in AI/ML or Data Analytics

The .size attribute can be used to check the total amount of data stored in an array.

For example, if an ML dataset has 100 samples and 5 features, its shape is (100, 5) and its size is 500.

This helps us understand the total number of values that need to be processed during data analysis or machine learning preprocessing.

It can also help identify unexpected changes in the amount of data after operations such as reshaping or filtering.

## Data Types

## Step 1 – Understand the Concept

A data type tells us what kind of values are stored in a NumPy array.

NumPy arrays can store different types of numerical data, such as:

- Integer (`int`) – whole numbers like `10`, `20`, and `30`.
- Float (`float`) – decimal numbers like `10.5`, `20.75`, and `30.2`.
- Boolean (`bool`) – `True` or `False`.

NumPy provides the `.dtype` attribute to check the data type of the elements in an array.

We can also specify a data type while creating an array by using the `dtype` parameter with functions such as `np.array()`.

For example:

`np.array([10, 20, 30], dtype=float)`

Data types are important because they determine how numerical data is stored and processed.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Think about different types of containers.

A container for water is different from a container for solid items.

Similarly, a data type tells NumPy what kind of values an array contains and how those values should be handled.

### 2. Simple Example

Consider an array containing whole numbers:

`[10, 20, 30, 40]`

These are integer values, so NumPy stores them using an integer data type.

For decimal values:

`[10.5, 20.5, 30.5]`

NumPy uses a floating-point data type.

### 3. Business Example

A business may store:

- Number of products sold → Integer
- Product price → Float
- Customer purchase status → Boolean

Choosing the appropriate data type helps store and process business data correctly.

### 4. AI/ML Use Case

AI/ML datasets contain many numerical features such as age, salary, product price, and transaction amount.

These values may be stored as integers or floating-point numbers.

Checking the data type helps us understand how the data is stored before preprocessing, calculations, and model training.

In [12]:
# Import NumPy
import numpy as np

# Create an integer array
integer_data = np.array([10, 20, 30, 40])

# Create a float array
float_data = np.array([10.5, 20.5, 30.5, 40.5])

# Display the data types
print(integer_data.dtype)
print(float_data.dtype)

int64
float64


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([10, 20, 30, 40])` creates a NumPy array containing whole numbers.
- `np.array([10.5, 20.5, 30.5, 40.5])` creates a NumPy array containing decimal numbers.
- `integer_data.dtype` checks the data type of the integer array.
- `float_data.dtype` checks the data type of the float array.
- `print()` displays the data types.

### What the Code Does

The code creates two NumPy arrays with different types of numerical values.

The first array contains whole numbers, so NumPy identifies it as an integer type.

The second array contains decimal numbers, so NumPy identifies it as a floating-point type.

### Why `.dtype` is Used

The `.dtype` attribute is used to find out what type of data is stored in a NumPy array.

It is useful when we need to understand how NumPy is storing the values and when we need to check whether the data type is suitable for a particular calculation or machine learning process.

`.dtype` is an attribute, so we write:

`array.dtype`

We do not write:

`array.dtype()`

### Expected Output

```text
int64
float64

The first output represents an integer data type because the array contains whole numbers.

The second output represents a floating-point data type because the array contains decimal numbers.

The exact integer type may vary depending on the system.

### Where It Is Used in AI/ML or Data Analytics

Data types are important when preparing data for AI/ML and Data Analytics.

For example, customer age may be stored as an integer, while income or product price may be stored as a floating-point value.

Before performing calculations or training a machine learning model, checking .dtype helps us identify whether the data is stored in an appropriate format.

Correct data types can also help avoid unexpected calculation errors and make numerical processing more efficient.

## Data Types

## Step 1 – Understand the Concept

A data type tells us what kind of values are stored in a NumPy array.

NumPy arrays can store different types of numerical data, such as:

- Integer (`int`) – whole numbers like `10`, `20`, and `30`.
- Float (`float`) – decimal numbers like `10.5`, `20.75`, and `30.2`.
- Boolean (`bool`) – `True` or `False`.

NumPy provides the `.dtype` attribute to check the data type of the elements in an array.

We can also specify a data type while creating an array by using the `dtype` parameter with functions such as `np.array()`.

For example:

`np.array([10, 20, 30], dtype=float)`

Data types are important because they determine how numerical data is stored and processed.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Think about different types of containers.

A container for water is different from a container for solid items.

Similarly, a data type tells NumPy what kind of values an array contains and how those values should be handled.

### 2. Simple Example

Consider an array containing whole numbers:

`[10, 20, 30, 40]`

These are integer values, so NumPy stores them using an integer data type.

For decimal values:

`[10.5, 20.5, 30.5]`

NumPy uses a floating-point data type.

### 3. Business Example

A business may store:

- Number of products sold → Integer
- Product price → Float
- Customer purchase status → Boolean

Choosing the appropriate data type helps store and process business data correctly.

### 4. AI/ML Use Case

AI/ML datasets contain many numerical features such as age, salary, product price, and transaction amount.

These values may be stored as integers or floating-point numbers.

Checking the data type helps us understand how the data is stored before preprocessing, calculations, and model training.

In [15]:
# Import NumPy
import numpy as np

# Create an integer array
integer_data = np.array([10, 20, 30, 40])

# Create a float array
float_data = np.array([10.5, 20.5, 30.5, 40.5])

# Display the data types
print(integer_data.dtype)
print(float_data.dtype)

int64
float64


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([10, 20, 30, 40])` creates a NumPy array containing whole numbers.
- `np.array([10.5, 20.5, 30.5, 40.5])` creates a NumPy array containing decimal numbers.
- `integer_data.dtype` checks the data type of the integer array.
- `float_data.dtype` checks the data type of the float array.
- `print()` displays the data types.

### What the Code Does

The code creates two NumPy arrays with different types of numerical values.

The first array contains whole numbers, so NumPy identifies it as an integer type.

The second array contains decimal numbers, so NumPy identifies it as a floating-point type.

### Why `.dtype` is Used

The `.dtype` attribute is used to find out what type of data is stored in a NumPy array.

It is useful when we need to understand how NumPy is storing the values and when we need to check whether the data type is suitable for a particular calculation or machine learning process.

`.dtype` is an attribute, so we write:

`array.dtype`

We do not write:

`array.dtype()`

### Expected Output

```text
int64
float64

The first output represents an integer data type because the array contains whole numbers.

The second output represents a floating-point data type because the array contains decimal numbers.

The exact integer type may vary depending on the system.    

### Where It Is Used in AI/ML or Data Analytics

Data types are important when preparing data for AI/ML and Data Analytics.

For example, customer age may be stored as an integer, while income or product price may be stored as a floating-point value.

Before performing calculations or training a machine learning model, checking .dtype helps us identify whether the data is stored in an appropriate format.

Correct data types can also help avoid unexpected calculation errors and make numerical processing more efficient.

## Indexing

## Step 1 – Understand the Concept

Indexing is used to access a specific element from a NumPy array using its position.

NumPy uses zero-based indexing, which means the first element has index `0`, the second element has index `1`, and so on.

For a 1D array, we use one index:

`array[index]`

For a 2D array, we use a row index and a column index:

`array[row, column]`

Square brackets `[]` are used for indexing.

Indexing is useful when we need to access, check, or use specific values from an array.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Think about seats in a row.

If the seats are numbered starting from 0, the first seat is seat 0, the second seat is seat 1, and the third seat is seat 2.

Similarly, NumPy uses positions starting from index 0 to access array elements.

### 2. Simple Example

Consider this array:

`[10, 20, 30, 40]`

The indexes are:

- Index 0 → 10
- Index 1 → 20
- Index 2 → 30
- Index 3 → 40

Therefore, `numbers[2]` returns `30`.

### 3. Business Example

A company stores daily sales:

`[5000, 7000, 6000, 8000]`

If we want to access the sales value for the third day, we can use index `2`.

`5000` → Day 1  
`7000` → Day 2  
`6000` → Day 3  
`8000` → Day 4

So, `sales[2]` returns `6000`.

### 4. AI/ML Use Case

In AI/ML, arrays contain numerical features and data values.

For example, a customer feature array may contain:

`[25, 45000, 3]`

where the values represent age, income, and number of purchases.

Indexing allows us to access a particular feature, such as the income value at index `1`.

In [16]:
# Import NumPy
import numpy as np

# Create a NumPy array
numbers = np.array([10, 20, 30, 40])

# Access elements using indexing
print(numbers[0])
print(numbers[2])

10
30


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([10, 20, 30, 40])` creates a NumPy array containing four values.
- `numbers[0]` accesses the element at index `0`, which is the first element.
- `numbers[2]` accesses the element at index `2`, which is the third element.
- `print()` displays the selected values.

### What the Code Does

The code creates a 1D NumPy array and uses indexing to access specific elements from the array.

The first element is accessed using index `0`, and the third element is accessed using index `2`.

### Why Indexing is Used

Indexing is used when we need to access a particular value from an array.

NumPy uses zero-based indexing, so the first element starts at index `0`.

For example:

`numbers[0]` → first element

`numbers[2]` → third element

Using indexing allows us to work with specific values without accessing the entire array.

### Expected Output

```text
10
30

10 is displayed because index 0 contains the value 10.

30 is displayed because index 2 contains the value 30.

### Where It Is Used in AI/ML or Data Analytics

Indexing is commonly used to access specific values from datasets and numerical arrays.

For example, an ML dataset may contain features such as age, income, and purchase amount.

Indexing can be used to access a particular feature or value from the dataset for analysis, preprocessing, or model input preparation.

It is also useful when checking individual values during data cleaning and debugging.

## Slicing

## Step 1 – Understand the Concept

Slicing is used to select a part or range of elements from a NumPy array.

The basic syntax for slicing is:

`array[start:stop:step]`

Where:

- `start` specifies the index where selection begins.
- `stop` specifies the index where selection ends.
- `step` specifies how many positions to move at a time.

The stop index is not included in the result.

For example:

`numbers[1:4]`

selects elements from index `1` up to, but not including, index `4`.

Slicing is useful when we need to work with a specific portion of numerical data instead of the complete array.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine a row of five books arranged from position 0 to position 4.

If we want to take only the books from position 1 to position 3, we can select that range instead of taking all five books.

Similarly, NumPy slicing allows us to select a specific range of elements from an array.

### 2. Simple Example

Consider this array:

`[10, 20, 30, 40, 50]`

If we use:

`numbers[1:4]`

NumPy selects:

`[20, 30, 40]`

The element at index 4 is not included.

### 3. Business Example

A company stores weekly sales:

`[5000, 7000, 6000, 8000, 9000, 7500, 8500]`

If we want to analyze sales from the second day to the fifth day, we can use slicing to select only that portion of the data.

This allows the company to perform analysis on a specific time period.

### 4. AI/ML Use Case

In AI/ML, datasets may contain many rows or features.

Slicing can be used to select a specific group of samples or a portion of features.

For example, we can select a subset of training data for analysis or testing without working with the entire array.

In [17]:
# Import NumPy
import numpy as np

# Create a NumPy array
numbers = np.array([10, 20, 30, 40, 50])

# Select elements from index 1 to index 3
selected_numbers = numbers[1:4]

# Display the selected elements
print(selected_numbers)

[20 30 40]


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([10, 20, 30, 40, 50])` creates a NumPy array containing five values.
- `numbers[1:4]` selects elements starting from index `1` and stops before index `4`.
- The selected values are stored in `selected_numbers`.
- `print()` displays the selected portion of the array.

### What the Code Does

The code creates a NumPy array and uses slicing to select a specific range of elements.

The array contains:

`[10, 20, 30, 40, 50]`

The slice `numbers[1:4]` selects the values at indexes `1`, `2`, and `3`.

Therefore, the result is:

`[20, 30, 40]`

### Why Slicing is Used

Slicing is used when we need to select a portion of an array without selecting each element separately.

The syntax:

`array[start:stop]`

allows us to specify the range we want.

In `numbers[1:4]`:

- `1` is the starting index.
- `4` is the stopping index.
- Index `4` is not included.

Slicing makes it easier to work with specific parts of large numerical datasets.

### Expected Output

```text
[20 30 40]

The output contains the values at indexes 1, 2, and 3.

The value at index 4, which is 50, is not included because the stop index is excluded.

### Where It Is Used in AI/ML or Data Analytics

Slicing is commonly used to select subsets of data during data analysis and machine learning.

For example, if a dataset contains thousands of records, slicing can be used to select a smaller group of rows for testing, analysis, or preprocessing.

It can also be used to select specific columns or features from an array.

For example, when preparing ML data, we may separate input features from a target value using array slicing.

## Reshaping

## Step 1 – Understand the Concept

Reshaping is the process of changing the dimensions or structure of a NumPy array without changing its elements.

For example, a 1D array containing 6 elements can be reshaped into a 2D array with 2 rows and 3 columns.

NumPy provides the `.reshape()` method to change the shape of an array.

The basic syntax is:

`array.reshape(rows, columns)`

The total number of elements must remain the same before and after reshaping.

For example:

`6 elements → 2 × 3 = 6 elements`

Reshaping is useful when we need to organize data into the required structure for calculations, analysis, or machine learning.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine having 6 books arranged in a single row.

We can rearrange the same 6 books into 2 rows with 3 books in each row.

The books have not changed. Only their arrangement has changed.

Similarly, reshaping changes the structure of an array without changing its values.

### 2. Simple Example

Consider this 1D array:

`[10, 20, 30, 40, 50, 60]`

It contains 6 elements.

We can reshape it into:

`[[10, 20, 30], [40, 50, 60]]`

The new shape is `(2, 3)`.

The values remain the same; only their arrangement changes.

### 3. Business Example

A company may initially store 12 monthly sales values in a 1D array.

The values can be reshaped into a 2D structure with 4 rows and 3 columns, depending on how the business wants to organize the data.

This makes it easier to perform calculations based on the required data structure.

### 4. AI/ML Use Case

In AI/ML, data often needs to be arranged in a specific shape before it is given to a model.

For example, image data may need to be reshaped into rows, columns, and channels.

Reshaping is also used when preparing feature data for machine learning algorithms.

In [18]:
# Import NumPy
import numpy as np

# Create a 1D array
numbers = np.array([10, 20, 30, 40, 50, 60])

# Reshape the array into 2 rows and 3 columns
reshaped_numbers = numbers.reshape(2, 3)

# Display the reshaped array
print(reshaped_numbers)

[[10 20 30]
 [40 50 60]]


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([10, 20, 30, 40, 50, 60])` creates a 1D NumPy array containing 6 elements.
- `numbers.reshape(2, 3)` changes the structure of the array into 2 rows and 3 columns.
- The reshaped array is stored in `reshaped_numbers`.
- `print()` displays the new structure of the array.

### What the Code Does

The code starts with a 1D array containing 6 elements.

It then uses `.reshape(2, 3)` to organize those same 6 elements into 2 rows and 3 columns.

The values are not changed. Only the structure of the array is changed.

### Why `.reshape()` is Used

The `.reshape()` method is used when we need to change the structure or dimensions of an array.

In this example:

`2 × 3 = 6`

The original array also contains 6 elements, so the reshape operation is valid.

If the number of elements does not match, NumPy will produce an error.

For example, trying to reshape 6 elements into `(2, 4)` is not possible because `2 × 4 = 8`.

### Expected Output

```text
[[10 20 30]
 [40 50 60]]

The output has 2 rows and 3 columns.

The original values 10, 20, 30, 40, 50, 60 are still present; they have only been rearranged into a 2D structure.

### Where It Is Used in AI/ML or Data Analytics

Reshaping is commonly used during data preprocessing in AI/ML.

For example, machine learning models often expect input data in a particular shape.

If we have 100 samples with 5 features, the data can have a shape of (100, 5).

Reshaping can also be useful for image data, where the data may need to be organized into height, width, and color channels before being given to an ML or deep learning model.

## Flatten

## Step 1 – Understand the Concept

Flattening is the process of converting a multi-dimensional NumPy array into a one-dimensional array.

For example, a 2D array with rows and columns can be converted into a single row of values.

NumPy provides the `.flatten()` method to convert an array into a 1D array.

The basic syntax is:

`array.flatten()`

Flattening does not change the values in the original array. It changes the structure by arranging all elements into one dimension.

Flattening is useful when data needs to be converted into a 1D structure for further processing or machine learning.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine books arranged on 2 shelves.

Each shelf contains several books, so the books are organized in rows.

If we take all the books from both shelves and place them into one long row, the books are still the same, but their arrangement becomes one-dimensional.

This is similar to flattening an array.

### 2. Simple Example

Consider this 2D array:

`[[10, 20, 30], [40, 50, 60]]`

It contains 2 rows and 3 columns.

After flattening, it becomes:

`[10, 20, 30, 40, 50, 60]`

The values remain the same, but the array becomes 1D.

### 3. Business Example

A company may store sales information in a table containing rows and columns.

If all the values need to be processed as one sequence, the 2D sales array can be flattened into a 1D array.

This can be useful for certain calculations or data processing tasks.

### 4. AI/ML Use Case

In AI/ML, image data is often represented using multiple dimensions.

For example, an image can contain rows, columns, and color channels.

Flattening can convert this structured data into a 1D sequence of values before passing it to certain machine learning models that expect a one-dimensional input.

In [19]:
# Import NumPy
import numpy as np

# Create a 2D array
data = np.array([[10, 20, 30], [40, 50, 60]])

# Flatten the array
flattened_data = data.flatten()

# Display the flattened array
print(flattened_data)

[10 20 30 40 50 60]


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([[10, 20, 30], [40, 50, 60]])` creates a 2D NumPy array with 2 rows and 3 columns.
- `data.flatten()` converts the 2D array into a 1D array.
- The flattened array is stored in `flattened_data`.
- `print()` displays the resulting 1D array.

### What the Code Does

The code creates a 2D array containing 6 elements arranged in 2 rows and 3 columns.

It then uses the `.flatten()` method to convert the 2D structure into a single 1D array.

The values are not changed. Only the structure of the array is changed.

### Why `.flatten()` is Used

The `.flatten()` method is used when we need to convert a multi-dimensional array into a one-dimensional array.

It is useful when a particular calculation, algorithm, or machine learning model requires data in a 1D format.

The method returns a flattened copy of the array.

### Expected Output

```text
[10 20 30 40 50 60]

The output contains all 6 elements from the original 2D array in a single dimension.

The original order of the values is maintained.

### Where It Is Used in AI/ML or Data Analytics

Flattening is commonly used in AI/ML when multi-dimensional data needs to be converted into a one-dimensional format.

For example, an image contains pixel values arranged in rows and columns. Before using the image with some traditional machine learning models, the pixel data can be flattened into a 1D array.

It is also useful during data preprocessing when a model expects a single sequence of numerical features.

## Copy vs View

## Step 1 – Understand the Concept

In NumPy, a copy and a view are two different ways of creating another array from an existing array.

A **copy** creates a completely separate array with its own data.

A **view** creates a new array object that refers to the same underlying data as the original array.

NumPy provides:

- `.copy()` – creates an independent copy of an array.
- `.view()` – creates a view of an existing array.

If we change a copy, the original array remains unchanged.

If we change a view, the original array can also be affected because they share the same underlying data.

Understanding the difference between copy and view is important when working with and modifying numerical data.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine you have an original document.

A **copy** is like making a photocopy of the document. You can write on the photocopy without changing the original document.

A **view** is like looking at the original document through a window. You are still looking at the same original information, so changes to that information can affect what you see.

### 2. Simple Example

Suppose we have:

`[10, 20, 30]`

If we create a copy and change its first value, the original remains:

`[10, 20, 30]`

But if we create a view and change its first value, the original array can also change.

### 3. Business Example

A company may have an original sales dataset.

If an analyst creates a copy before making changes, the original sales data remains safe.

If the analyst works with a view and changes values, the original data may also be changed.

Using the correct option helps protect important business data.

### 4. AI/ML Use Case

In AI/ML, we often create different versions of datasets during preprocessing.

A copy can be useful when we want to modify data without changing the original dataset.

A view can be useful when we want another way to access the same data without creating a separate copy.

Understanding this difference helps prevent unexpected changes during data preprocessing.

In [20]:
# Import NumPy
import numpy as np

# Create the original array
original = np.array([10, 20, 30])

# Create a copy
copied = original.copy()

# Change the copied array
copied[0] = 100

# Create a view
viewed = original.view()

# Change the viewed array
viewed[1] = 200

# Display the arrays
print("Original:", original)
print("Copy:", copied)
print("View:", viewed)

Original: [ 10 200  30]
Copy: [100  20  30]
View: [ 10 200  30]


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([10, 20, 30])` creates the original NumPy array.
- `original.copy()` creates an independent copy of the original array.
- `copied[0] = 100` changes the first value of the copy.
- `original.view()` creates a view that refers to the same underlying data as the original array.
- `viewed[1] = 200` changes the second value through the view.
- `print()` displays the original array, copy, and view.

### What the Code Does

The code demonstrates the difference between a copy and a view.

First, an original array is created.

Then a copy is created and modified. The change made to the copy does not affect the original array.

Next, a view is created and modified. Because the view shares the underlying data with the original array, the change is also reflected in the original array.

### Why `.copy()` and `.view()` are Used

The `.copy()` method is used when we need a completely independent array.

The `.view()` method is used when we need another array object that refers to the same underlying data.

Using `.copy()` is useful when the original data must be protected from changes.

Using `.view()` can be useful when we want to work with the same data without creating a separate data copy.

### Expected Output

```text
Original: [ 10 200  30]
Copy: [100  20  30]
View: [ 10 200  30]

The copy changes from 10 to 100, but the original remains 10.

The view changes the second value from 20 to 200, and this change is also visible in the original array.

### Where It Is Used in AI/ML or Data Analytics

Copy and view are important when working with datasets during preprocessing.

For example, if we want to normalize or modify a dataset while keeping the original data unchanged, we can create a copy before making the changes.

Views can be useful when working with large arrays because they can avoid creating another complete copy of the data.

Understanding when to use a copy or view helps prevent accidental changes to original datasets and can also improve memory usage when working with large numerical data.

## Broadcasting

## Step 1 – Understand the Concept

Broadcasting is a NumPy feature that allows arithmetic operations between arrays of different shapes when their shapes are compatible.

It allows NumPy to automatically adjust or expand values during an operation without creating a separate array manually.

Broadcasting can be used when performing operations such as:

- Addition `+`
- Subtraction `-`
- Multiplication `*`
- Division `/`

For example:

`numbers + 5`

NumPy applies `5` to every element of the array.

Broadcasting makes numerical calculations shorter, easier, and more efficient.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine a teacher giving every student an additional 5 marks.

Instead of manually adding 5 to each student's mark, we can think of the teacher applying the same instruction to everyone at once.

Similarly, NumPy can apply one value to every element of an array using broadcasting.

### 2. Simple Example

Consider the array:

`[10, 20, 30]`

If we add `5`:

`[10, 20, 30] + 5`

NumPy automatically applies `5` to every element.

The result is:

`[15, 25, 35]`

### 3. Business Example

A company has product prices:

`[100, 200, 300]`

If the company wants to increase every price by `10`, broadcasting allows us to write:

`prices + 10`

The result is:

`[110, 210, 310]`

This makes it easy to apply the same calculation to many business values.

### 4. AI/ML Use Case

Broadcasting is frequently used in AI/ML data preprocessing.

For example, we may need to subtract a common value from every feature or apply a mathematical operation to all values in a dataset.

Broadcasting allows these operations to be performed efficiently without writing loops for every element.

In [21]:
# Import NumPy
import numpy as np

# Create a NumPy array
prices = np.array([100, 200, 300])

# Add 10 to every price using broadcasting
updated_prices = prices + 10

# Display the updated prices
print(updated_prices)

[110 210 310]


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([100, 200, 300])` creates a NumPy array containing three product prices.
- `prices + 10` adds the value `10` to every element of the array using NumPy broadcasting.
- The result is stored in `updated_prices`.
- `print()` displays the updated prices.

### What the Code Does

The code creates an array containing three product prices.

It then adds `10` to the entire array at once.

NumPy automatically applies the value `10` to each element:

`100 + 10 = 110`

`200 + 10 = 210`

`300 + 10 = 310`

We do not need to write a separate loop for each value.

### Why Broadcasting is Used

Broadcasting is used to perform operations between arrays and individual values, or between compatible arrays, without manually repeating the values.

In this example, the single value `10` is automatically applied to all three elements.

This makes the code shorter and allows NumPy to perform numerical operations efficiently.

### Expected Output

```text
[110 210 310]

The output shows that 10 has been added to every price in the original array.

The original prices were:

[100, 200, 300]

The updated prices are:

[110, 210, 310]

### Where It Is Used in AI/ML or Data Analytics

Broadcasting is widely used in AI/ML and Data Analytics for numerical calculations and data preprocessing.

For example, when preparing a dataset, we may need to subtract a mean value from every data point or divide values by a common value during normalization.

Broadcasting allows these operations to be applied across large arrays efficiently without writing separate loops for every element.

# Array Operations

## Step 1 – Understand the Concept

Array operations are mathematical operations performed on the elements of NumPy arrays.

NumPy allows us to perform operations directly on arrays without writing separate loops.

Common array operations include:

- Addition `+` – adds corresponding elements.
- Subtraction `-` – subtracts corresponding elements.
- Multiplication `*` – multiplies corresponding elements.
- Division `/` – divides corresponding elements.

When two arrays have the same shape, NumPy performs these operations element by element.

For example:

`[10, 20, 30] + [1, 2, 3]`

gives:

`[11, 22, 33]`

Array operations are useful for performing numerical calculations quickly and efficiently.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine two boxes containing the same number of items.

If the first box has `[10, 20, 30]` items and the second box has `[1, 2, 3]` items, we can compare or combine the items at the same position.

NumPy performs the operation between corresponding elements automatically.

### 2. Simple Example

Consider two arrays:

`[10, 20, 30]`

and

`[1, 2, 3]`

Addition gives:

`[11, 22, 33]`

because:

- `10 + 1 = 11`
- `20 + 2 = 22`
- `30 + 3 = 33`

### 3. Business Example

A company may have the original prices of three products and their additional charges.

Original prices:

`[100, 200, 300]`

Additional charges:

`[10, 20, 30]`

Adding these arrays gives the final prices:

`[110, 220, 330]`

This allows calculations to be performed on multiple products at the same time.

### 4. AI/ML Use Case

In AI/ML, numerical data is stored in arrays.

Array operations can be used during data preprocessing, feature calculations, mathematical transformations, and model-related calculations.

For example, values from two numerical features can be added, subtracted, multiplied, or divided element by element.

In [22]:
# Import NumPy
import numpy as np

# Create two NumPy arrays
array_a = np.array([10, 20, 30])
array_b = np.array([1, 2, 3])

# Perform array operations
addition = array_a + array_b
subtraction = array_a - array_b
multiplication = array_a * array_b
division = array_a / array_b

# Display the results
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([10, 20, 30])` creates the first NumPy array.
- `np.array([1, 2, 3])` creates the second NumPy array.
- `array_a + array_b` adds corresponding elements of both arrays.
- `array_a - array_b` subtracts corresponding elements.
- `array_a * array_b` multiplies corresponding elements.
- `array_a / array_b` divides corresponding elements.
- `print()` displays the results of each operation.

### What the Code Does

The code creates two NumPy arrays with the same shape.

It then performs four mathematical operations element by element.

For addition:

`[10, 20, 30] + [1, 2, 3]`

gives:

`[11, 22, 33]`

For subtraction:

`[10, 20, 30] - [1, 2, 3]`

gives:

`[9, 18, 27]`

For multiplication:

`[10, 20, 30] * [1, 2, 3]`

gives:

`[10, 40, 90]`

For division:

`[10, 20, 30] / [1, 2, 3]`

gives:

`[10. 10. 10.]`

### Why Array Operations Are Used

Array operations allow us to perform calculations on multiple values at the same time.

Instead of using a loop to process every element individually, NumPy performs the operation directly on the arrays.

This makes numerical calculations simpler, shorter, and efficient.

### Expected Output

```text
Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]

The output shows that each operation was performed between the corresponding elements of the two arrays.

### Where It Is Used in AI/ML or Data Analytics

Array operations are widely used in AI/ML and Data Analytics for numerical calculations.

They are useful for data preprocessing, feature calculations, mathematical transformations, and preparing numerical data for machine learning models.

For example, multiple feature values can be transformed or calculated together using NumPy array operations.

# Universal Functions (ufuncs)

## Step 1 – Understand the Concept

Universal Functions, also called ufuncs, are NumPy functions that perform mathematical operations element by element on NumPy arrays.

They allow us to apply the same function to every element of an array without writing a separate loop.

Some common NumPy ufuncs are:

- `np.sqrt()` – calculates the square root.
- `np.abs()` – returns the absolute value.
- `np.exp()` – calculates the exponential value.
- `np.log()` – calculates the natural logarithm.
- `np.sin()` – calculates the sine value.
- `np.cos()` – calculates the cosine value.

For example:

`np.sqrt([1, 4, 9])`

gives:

`[1. 2. 3.]`

Ufuncs make mathematical calculations on numerical data simple and efficient.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine a teacher wants to calculate the square root of every number in a list.

Instead of calculating each number separately, the teacher applies the same calculation to all numbers.

Similarly, a NumPy ufunc applies the same mathematical function to every element of an array.

### 2. Simple Example

Consider the array:

`[1, 4, 9, 16]`

Using `np.sqrt()` gives:

`[1. 2. 3. 4.]`

The same square root operation is applied to every element.

### 3. Business Example

A business may have numerical values representing product quantities:

`[100, 400, 900, 1600]`

A ufunc such as `np.sqrt()` can be applied to all values at once when a mathematical transformation is required for analysis.

### 4. AI/ML Use Case

Ufuncs are useful in AI/ML for mathematical transformations and data preprocessing.

For example, functions such as `np.sqrt()`, `np.log()`, and `np.abs()` can be applied to numerical features to transform data before using it in machine learning models.

In [23]:
# Import NumPy
import numpy as np

# Create a NumPy array
numbers = np.array([1, 4, 9, 16])

# Calculate the square root of each element
square_roots = np.sqrt(numbers)

# Display the result
print(square_roots)

[1. 2. 3. 4.]


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([1, 4, 9, 16])` creates a NumPy array containing four numerical values.
- `np.sqrt(numbers)` applies the square root function to every element of the array.
- The result is stored in `square_roots`.
- `print()` displays the calculated square roots.

### What the Code Does

The code creates an array containing:

`[1, 4, 9, 16]`

Then `np.sqrt()` calculates the square root of every value:

- √1 = 1
- √4 = 2
- √9 = 3
- √16 = 4

The function is applied to all elements at the same time.

### Why `np.sqrt()` Is Used

`np.sqrt()` is a NumPy universal function used to calculate the square root of each element in an array.

It avoids the need to write a separate loop for every value and makes numerical calculations easier and more efficient.

### Expected Output

```text
[1. 2. 3. 4.]

The decimal points appear because NumPy returns the square-root results as floating-point values.



### Where It Is Used in AI/ML or Data Analytics

Ufuncs are commonly used in AI/ML and Data Analytics for mathematical transformations and numerical preprocessing.

For example, np.sqrt() can be used to transform numerical features, while functions such as np.log() and np.abs() can be useful for handling and transforming numerical data before analysis or machine learning.